Needed <- c("tm", "SnowballCC", "RColorBrewer", "ggplot2", "wordcloud", "biclust", "cluster", "igraph", "fpc")   
install.packages(Needed, dependencies=TRUE)   
install.packages("Rcampdf", repos = "http://datacube.wu.ac.at/", type = "source")  
Sys.setlocale("LC_ALL","Chinese")
cname <- file.path("G:", "WPI_DS/DS502/R_For_DS502/Use_R_forTwitterAPI")   
##cname   
dir(cname) 
library(tm)   
docs <- Corpus(DirSource(cname))  
summary(docs)
docs <- tm_map(docs, removePunctuation)  
for(j in seq(docs))   
{   
  docs[[j]] <- gsub("/", " ", docs[[j]])   
  docs[[j]] <- gsub("@", " ", docs[[j]])   
  docs[[j]] <- gsub("\\|", " ", docs[[j]])   
}   
docs <- tm_map(docs, removeNumbers) 
docs <- tm_map(docs, tolower)
docs <- tm_map(docs, removeWords, stopwords("english")) 
library(SnowballC)   
docs <- tm_map(docs, stemDocument)
docs <- tm_map(docs, stripWhitespace)
docs <- tm_map(docs, PlainTextDocument)
docs <- iconv(docs, 'UTF-8', 'ASCII')
dtm <- DocumentTermMatrix(docs)   
dtm   
tdm <- TermDocumentMatrix(docs)   
##tdm 
freq <- colSums(as.matrix(dtm))   
length(freq) 
ord <- order(freq)  
m <- as.matrix(dtm)   
dim(m)   
write.csv(m, file="dtm.csv")
dtms <- removeSparseTerms(dtm, 0.1)
inspect(dtms) 
freq <- sort(colSums(as.matrix(dtm)), decreasing=TRUE)   
head(freq, 25) 
wf <- data.frame(word=names(freq), freq=freq)   
head(wf) 
library(ggplot2)   
p <- ggplot(subset(wf, freq>25), aes(word, freq))    
p <- p + geom_bar(stat="identity")   
p <- p + theme(axis.text.x=element_text(angle=45, hjust=1))   
p 